### ISSUE TITLE
Add OU value to Group Member Relationship field field_course_ou

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/group-lms-user-sync#2]
https://github.com/learnfullabs/group-lms-user-sync/blob/8d1456471bd2a0ad74bd2c5de1570fa6075ac7d2/src/GroupLMSUserSyncAPI.php#L81

### Acceptance Criteria

1. The Group Membership entity has a field called field_course_ou: https://dev-groupsite.learnful.io/admin/group/content/manage/course-group_membership/fields
2. This field should be populated for each Member that gets added via this module: https://dev-groupsite.learnful.io/group/1/content/3/edit?destination=/group/1/members
3. This is important because it will help us unenroll members in the future.

##### 1. Fields that are part of the member relationship entity for a group
<img width="1795" alt="image" src="https://github.com/learnfullabs/group-lms-user-sync/assets/3291625/f08deec5-6ab0-431c-b483-50bdfd6502ce">

##### 2. These fields are included when adding/modifying a member in a group
<img width="1817" alt="image" src="https://github.com/learnfullabs/group-lms-user-sync/assets/3291625/045fb38c-0865-439a-9ac3-fecebd715ccc">

##### 3. The value of field_course_ou for a Member is used to display/filter members:
<img width="1830" alt="image" src="https://github.com/learnfullabs/group-lms-user-sync/assets/3291625/99f5421c-316e-4cb6-af0d-c99db6c86611">

In future, we will also rely on the value of field_course_ou for a member to determine if we remove them from the course.

**Comment by danrod96** [comment]
if the OU field in the group member entity is changed somehow, implement a post update hook (?) to look for old value, loop through the groups to check if the user is still in that group identified with that OU, and if so, remove the user from the group
