### ISSUE TITLE
New Feature: Report & Log

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/group-lms-user-sync#9]
Acceptance Criteria:

1. All actions of adding/removing members from Groups should be logged.
2. The log should exists as a page available at path /admin/group/reports/enrollments.
3. The log should be built using Views and be paged, filterable, and easy to customize.
4. The View columns for the log: 1) Date, OU, Group, User Name, Enroll/UnEnrol
5. A report should be generated every day (morning) with all of the Group Member modifications since the last Report.

Similar to: https://studio.camerisefsl.ca/admin/migrate/log_ui/migration

**Comment by danrod96** [comment]
To be completed tomorrow/June 2nd.

**Comment by danrod96** [comment]
Thinking of Creating an Entity for logging all the Group LMS Enroll/UnEnroll events

**Comment by danrod96** [comment]
Attached is view that displays the enrolled/unenrolled events, I still need to create a hook (or perhaps implementing an Event Subscriber) to look for "unenroll" group events and record them

![grouplog1](https://github.com/learnfullabs/group-lms-user-sync/assets/8920224/c18934c4-002e-4662-9a68-d8ebb065094a)
![grouplog2](https://github.com/learnfullabs/group-lms-user-sync/assets/8920224/d232f751-fb9e-44f8-a2f4-280366b92b6e)
